[project]
name = "VSU"
version = "0.1.0"
description = "my first toml-file"
readme = "README.md"
requires-python = ">=3.12"
authors = [{name = 'Tafincev Dmitry', email = 'tafincev05@gmail.com'}]
dependencies = ['fastapi[standard]']
